# Generated by Django 4.1 on 2022-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_fathername', models.CharField(max_length=50)),
                ('student_mothername', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_phoneno', models.IntegerField(max_length=50)),
                ('student_dob', models.DateField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('student_picture', models.CharField(max_length=50)),
            ],
        ),
    ]
