# Generated by Django 4.1 on 2022-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_phoneno',
            field=models.IntegerField(),
        ),
    ]
