# Generated by Django 4.1 on 2022-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techops', '0002_alter_student_student_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_picture',
            field=models.CharField(max_length=255),
        ),
    ]
