# Generated by Django 4.1 on 2022-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techops', '0003_alter_student_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50)),
                ('faculty_email', models.EmailField(max_length=50)),
                ('faculty_status', models.CharField(max_length=50)),
                ('faculty_password', models.CharField(max_length=50)),
            ],
        ),
    ]
